export const SPECIALIZATIONS = [
  "cardiology",
  "family_medicine",
  "internal_medicine",
  "anesthesiology",
  "surgery",
  "orthopedics",
  "gynecology",
  "pediatrics",
  "neurology",
  "psychiatry",
  "radiology",
  "emergency_medicine",
  "laboratory_diagnostics",
  "dentistry",
  "dermatology",
  "ophthalmology",
  "oncology",
  "interdisciplinary"
] as const;

export const SPECIALIZATION_LABELS: Record<typeof SPECIALIZATIONS[number], string> = {
  cardiology: "Kardiologia",
  family_medicine: "Medycyna Rodzinna",
  internal_medicine: "Interna",
  anesthesiology: "Anestezjologia i Intensywna Terapia",
  surgery: "Chirurgia",
  orthopedics: "Ortopedia",
  gynecology: "Ginekologia i Położnictwo",
  pediatrics: "Pediatria",
  neurology: "Neurologia",
  psychiatry: "Psychiatria",
  radiology: "Radiologia",
  emergency_medicine: "Medycyna Ratunkowa",
  laboratory_diagnostics: "Diagnostyka Laboratoryjna",
  dentistry: "Stomatologia",
  dermatology: "Dermatologia",
  ophthalmology: "Okulistyka",
  oncology: "Onkologia",
  interdisciplinary: "Interdyscyplinarne / Inne"
};

export const EVENT_TAGS = [
  "webinar",
  "points",
  "free",
  "paid",
  "residents",
  "workshop",
  "congress",
  "conference",
  "symposium",
  "online",
  "hybrid",
  "advanced",
  "basic_level",
  "practical",
  "certification",
  "hands_on",
  "case_studies",
  "live_surgery",
  "networking"
] as const;

export const TAG_LABELS: Record<typeof EVENT_TAGS[number], string> = {
  webinar: "Webinar",
  points: "Punkty edukacyjne",
  free: "Bezpłatne",
  paid: "Płatne",
  residents: "Dla rezydentów",
  workshop: "Warsztaty",
  congress: "Kongres",
  conference: "Konferencja",
  symposium: "Sympozjum",
  online: "Online",
  hybrid: "Hybrydowe",
  advanced: "Zaawansowane",
  basic_level: "Podstawowe",
  practical: "Praktyczne",
  certification: "Z certyfikatem",
  hands_on: "Hands-on",
  case_studies: "Case studies",
  live_surgery: "Live surgery",
  networking: "Networking"
};

export const SPECIALIZATION_COLORS: Record<typeof SPECIALIZATIONS[number], string> = {
  cardiology: "!bg-red-100 !text-red-700 border border-red-200",
  family_medicine: "!bg-green-100 !text-green-700 border border-green-200",
  internal_medicine: "!bg-blue-100 !text-blue-700 border border-blue-200",
  anesthesiology: "!bg-purple-100 !text-purple-700 border border-purple-200",
  surgery: "!bg-orange-100 !text-orange-700 border border-orange-200",
  orthopedics: "!bg-amber-100 !text-amber-700 border border-amber-200",
  gynecology: "!bg-pink-100 !text-pink-700 border border-pink-200",
  pediatrics: "!bg-cyan-100 !text-cyan-700 border border-cyan-200",
  neurology: "!bg-indigo-100 !text-indigo-700 border border-indigo-200",
  psychiatry: "!bg-violet-100 !text-violet-700 border border-violet-200",
  radiology: "!bg-slate-200 !text-slate-700 border border-slate-300",
  emergency_medicine: "!bg-rose-100 !text-rose-700 border border-rose-200",
  laboratory_diagnostics: "!bg-teal-100 !text-teal-700 border border-teal-200",
  dentistry: "!bg-sky-100 !text-sky-700 border border-sky-200",
  dermatology: "!bg-fuchsia-100 !text-fuchsia-700 border border-fuchsia-200",
  ophthalmology: "!bg-emerald-100 !text-emerald-700 border border-emerald-200",
  oncology: "!bg-yellow-100 !text-yellow-700 border border-yellow-200",
  interdisciplinary: "!bg-gray-200 !text-gray-700 border border-gray-300"
};

export const VOIVODESHIPS = [
  "dolnoslaskie",
  "kujawsko_pomorskie", 
  "lubelskie",
  "lubuskie",
  "lodzkie",
  "malopolskie",
  "mazowieckie",
  "opolskie",
  "podkarpackie",
  "podlaskie",
  "pomorskie",
  "slaskie",
  "swietokrzyskie",
  "warminsko_mazurskie",
  "wielkopolskie",
  "zachodniopomorskie"
] as const;

export const VOIVODESHIP_LABELS: Record<typeof VOIVODESHIPS[number], string> = {
  dolnoslaskie: "Dolnośląskie",
  kujawsko_pomorskie: "Kujawsko-Pomorskie",
  lubelskie: "Lubelskie",
  lubuskie: "Lubuskie",
  lodzkie: "Łódzkie",
  malopolskie: "Małopolskie",
  mazowieckie: "Mazowieckie",
  opolskie: "Opolskie",
  podkarpackie: "Podkarpackie",
  podlaskie: "Podlaskie",
  pomorskie: "Pomorskie",
  slaskie: "Śląskie",
  swietokrzyskie: "Świętokrzyskie",
  warminsko_mazurskie: "Warmińsko-Mazurskie",
  wielkopolskie: "Wielkopolskie",
  zachodniopomorskie: "Zachodniopomorskie"
};

export const MAJOR_CITIES = [
  "warszawa",
  "krakow",
  "lodz",
  "wroclaw",
  "poznan",
  "gdansk",
  "szczecin",
  "bydgoszcz",
  "lublin",
  "bialystok",
  "katowice",
  "gdynia",
  "czestochowa",
  "radom",
  "sosnowiec",
  "torun",
  "kielce",
  "rzeszow",
  "gliwice",
  "zabrze",
  "olsztyn",
  "bielsko_biala",
  "bytom",
  "zielona_gora",
  "rybnik",
  "ruda_slaska",
  "opole",
  "tychy",
  "gorzow_wielkopolski",
  "elblag",
  "plock",
  "dabrowa_gornicza",
  "walbrzych",
  "wloclawek",
  "tarnow",
  "chorzow",
  "koszalin",
  "kalisz",
  "legnica",
  "grudziadz"
] as const;

export const CITY_LABELS: Record<typeof MAJOR_CITIES[number], string> = {
  warszawa: "Warszawa",
  krakow: "Kraków",
  lodz: "Łódź",
  wroclaw: "Wrocław",
  poznan: "Poznań",
  gdansk: "Gdańsk",
  szczecin: "Szczecin",
  bydgoszcz: "Bydgoszcz",
  lublin: "Lublin",
  bialystok: "Białystok",
  katowice: "Katowice",
  gdynia: "Gdynia",
  czestochowa: "Częstochowa",
  radom: "Radom",
  sosnowiec: "Sosnowiec",
  torun: "Toruń",
  kielce: "Kielce",
  rzeszow: "Rzeszów",
  gliwice: "Gliwice",
  zabrze: "Zabrze",
  olsztyn: "Olsztyn",
  bielsko_biala: "Bielsko-Biała",
  bytom: "Bytom",
  zielona_gora: "Zielona Góra",
  rybnik: "Rybnik",
  ruda_slaska: "Ruda Śląska",
  opole: "Opole",
  tychy: "Tychy",
  gorzow_wielkopolski: "Gorzów Wielkopolski",
  elblag: "Elbląg",
  plock: "Płock",
  dabrowa_gornicza: "Dąbrowa Górnicza",
  walbrzych: "Wałbrzych",
  wloclawek: "Włocławek",
  tarnow: "Tarnów",
  chorzow: "Chorzów",
  koszalin: "Koszalin",
  kalisz: "Kalisz",
  legnica: "Legnica",
  grudziadz: "Grudziądz"
};

export const CITY_TO_VOIVODESHIP: Record<typeof MAJOR_CITIES[number], typeof VOIVODESHIPS[number]> = {
  warszawa: "mazowieckie",
  krakow: "malopolskie",
  lodz: "lodzkie",
  wroclaw: "dolnoslaskie",
  poznan: "wielkopolskie",
  gdansk: "pomorskie",
  szczecin: "zachodniopomorskie",
  bydgoszcz: "kujawsko_pomorskie",
  lublin: "lubelskie",
  bialystok: "podlaskie",
  katowice: "slaskie",
  gdynia: "pomorskie",
  czestochowa: "slaskie",
  radom: "mazowieckie",
  sosnowiec: "slaskie",
  torun: "kujawsko_pomorskie",
  kielce: "swietokrzyskie",
  rzeszow: "podkarpackie",
  gliwice: "slaskie",
  zabrze: "slaskie",
  olsztyn: "warminsko_mazurskie",
  bielsko_biala: "slaskie",
  bytom: "slaskie",
  zielona_gora: "lubuskie",
  rybnik: "slaskie",
  ruda_slaska: "slaskie",
  opole: "opolskie",
  tychy: "slaskie",
  gorzow_wielkopolski: "lubuskie",
  elblag: "warminsko_mazurskie",
  plock: "mazowieckie",
  dabrowa_gornicza: "slaskie",
  walbrzych: "dolnoslaskie",
  wloclawek: "kujawsko_pomorskie",
  tarnow: "malopolskie",
  chorzow: "slaskie",
  koszalin: "zachodniopomorskie",
  kalisz: "wielkopolskie",
  legnica: "dolnoslaskie",
  grudziadz: "kujawsko_pomorskie"
};
